### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by nanfangshuo** [KaleW515/bupt-clockIn#3]
请问为啥按照readme操作后commit成功了，但workflow中只有对于主分支的更新，没有bupt-clockln的workflow呢

**Comment by KaleW515** [comment]
刚fork没有bupt-clockIn的workflow是正常的。
名称为bupt-clockIn的workflow表示触发了定时任务，如果你没有修改cron，那么默认是会在每天的00:01触发任务。

**Comment by nanfangshuo** [comment]
谢谢学长的脚本，今早起来之后确实正常运行！

**Comment by nanfangshuo** [comment]
谢谢学长，今早起来后正常运行！请问如果地点变更了比如返校了，有一些栏的信息要更改这个脚本还能用吗

**Comment by KaleW515** [comment]
目前的逻辑是读取前一天的信息，只变更日期然后进行提交，所以如果地点变更，需要先手动打卡一次，我可能需要完善一下readme。后面我也可能会更新功能使地点切换更顺畅

**Comment by nanfangshuo** [comment]
感谢！
